### PR TITLE
Upstream 3.7, patch fixes

### PR DESCRIPTION
**Pull request by aderbenev**
Suggested for https://github.com/epicsdeb/calc/issues/1
This builds with asyn 4.33

### CODE REVIEW

**Comment by mdavidsaver** [comment]
@aderbenev I don't have time/support for reviewing package updates.  Maybe @dchabot or @mark0n can?

**Review by mark0n — CHANGES_REQUESTED** [review]
Please bump up the version in the package names (`debian/control`).

**Comment by aderbenev** [comment]
Good catch, new commit addresses that.

**Review by mark0n — APPROVED** [review]

**Comment by mark0n** [comment]
@aderbenev, could you please also update the `pristine-tar` branch? No need to create a PR for `upstream` and `pristine-tar` - I usually just push them manually together with the new tags when the PR into `master` gets merged.

**Pull request merged**
